# Generated by Django 3.0.3 on 2021-01-19 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512)),
                ('data', models.BinaryField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512)),
                ('type', models.CharField(max_length=64)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512)),
                ('model', models.BinaryField()),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vb_django.Experiment')),
            ],
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=512)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vb_django.Project')),
            ],
        ),
        migrations.CreateModel(
            name='PipelineParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('vtype', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=128)),
                ('options', models.CharField(max_length=512)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vb_django.Pipeline')),
            ],
        ),
        migrations.CreateModel(
            name='PipelineMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=512)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vb_django.Pipeline')),
            ],
        ),
        migrations.CreateModel(
            name='ModelMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=512)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vb_django.Model')),
            ],
        ),
        migrations.CreateModel(
            name='LocationMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=512)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vb_django.Location')),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=512)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vb_django.Experiment')),
            ],
        ),
        migrations.AddField(
            model_name='experiment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vb_django.Project'),
        ),
        migrations.CreateModel(
            name='DatasetMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=512)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vb_django.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='AccessControlList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_user', models.CharField(max_length=32)),
                ('object', models.CharField(max_length=32)),
                ('object_type', models.CharField(choices=[('Project', 'Project'), ('Location', 'Location'), ('Experiment', 'Experiment'), ('Dataset', 'Dataset'), ('Model', 'Model')], max_length=16)),
                ('expiration', models.DateTimeField()),
                ('access_type', models.CharField(choices=[('Read', 'Read'), ('Write', 'Write')], max_length=8)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
