# Generated by Django 3.0.3 on 2020-11-06 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=512)),
                ('variables', models.CharField(blank=True, max_length=512, null=True)),
                ('model', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512)),
                ('data', models.BinaryField()),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512)),
                ('type', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=512)),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vb_django.Project')),
            ],
        ),
        migrations.CreateModel(
            name='PreProcessingConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('config', models.CharField(max_length=512)),
                ('analytical_model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vb_django.AnalyticalModel')),
            ],
        ),
        migrations.CreateModel(
            name='ModelResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_id', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField()),
                ('result', models.FloatField()),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vb_django.AnalyticalModel')),
            ],
        ),
        migrations.CreateModel(
            name='ModelMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=512)),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vb_django.AnalyticalModel')),
            ],
        ),
        migrations.CreateModel(
            name='LocationMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=512)),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vb_django.Location')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vb_django.Project'),
        ),
        migrations.CreateModel(
            name='DatasetMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=512)),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vb_django.Dataset')),
            ],
        ),
        migrations.AddField(
            model_name='analyticalmodel',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vb_django.Project'),
        ),
        migrations.CreateModel(
            name='AccessControlList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_user_id', models.CharField(max_length=32)),
                ('object_id', models.CharField(max_length=32)),
                ('object_type', models.CharField(choices=[('Project', 'Project'), ('Location', 'Location'), ('AnalyticalModel', 'AnalyticalModel'), ('Dataset', 'Dataset')], max_length=16)),
                ('expiration', models.DateTimeField()),
                ('access_type', models.CharField(choices=[('Read', 'Read'), ('Write', 'Write')], max_length=8)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
