# Generated by Django 3.0.3 on 2020-11-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vb_django', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='location_id',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
