# Generated by Django 3.0.3 on 2020-11-06 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vb_django', '0002_auto_20201106_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analyticalmodel',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='preprocessingconfig',
            old_name='analytical_model_id',
            new_name='analytical_model',
        ),
    ]
